### ISSUE TITLE
search issue for flipkart in the soucre code u provided

### ISSUE THREAD

**Issue by shubham0976** [Abhayparashar31/price-compare-app#1]
I run the souce code and the program is running well but flipkart search always shows product not found. for example  i searched a product redmi 8 and it showed product not found but when i click the  link it redirects me to the product page on flipkart. redmi 8 is available on flipkart kindly look the screenshots for clearity of issue.
![Screenshot (27)](https://user-images.githubusercontent.com/74960251/100078441-87387500-2e69-11eb-9d57-b985e4ce1407.png)
![Screenshot (26)](https://user-images.githubusercontent.com/74960251/100078463-8e5f8300-2e69-11eb-84a8-87bfa3761171.png)
thanking  you 
shubham gupta

**Comment by Abhayparashar31** [comment]
It's not the issue with the program it's with Flipkart they have recently change the class names for their product names now I have also updated the class names in the code it is working fine now.. 
![28 11 2020_17 58 19_REC](https://user-images.githubusercontent.com/52857736/100515603-57f47180-31a3-11eb-938a-90cca6765b30.png)
